---
title: Gary Peters
timezone: Pacific/Auckland

collections:
  posts:
    title: Posts
    output: true



email: hello@garypeters.info

description: Gary Peters makes painting-objects, monochromes, site responsive installations, and non-objective wall works.

baseurl:
url:
# twitter_username: jekyllrb
# github_username: jekyll
markdown: kramdown

# theme: jekyll-theme-primer
# theme: minima

plugins:
- jekyll-feed
- jekyll-seo-tag
# - jekyll-paginate-v2


collections:
  works:
    output: true
  uploads:
  output: true



# Produces a cleaner folder structure when using categories
# permalink: /:year/:month/:title.html

# Explicitly turn off the old code
##paginate: nil
##paginate_path: nil

# Pagination Settings
# pagination:
#   enabled: true
#   per_page: 2
#   permalink: '/posts/:num/'
#   title: ':title - posts :num of :max'
#   limit: 0
#   sort_field: 'date'
#   sort_reverse: true
